// examples/sample-angular-app/src/app/app.component.ts
// Angular modules
import { Component, CUSTOM_ELEMENTS_SCHEMA, type OnInit } from '@angular/core';
import { DAppKitUI } from '@vechain/dapp-kit-ui';

@Component({
    selector: 'app-root',
    standalone: true,
    templateUrl: './app.component.html',
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppComponent implements OnInit {
    // -------------------------------------------------------------------------------
    // NOTE Init ---------------------------------------------------------------------
    // -------------------------------------------------------------------------------

    public ngOnInit(): void {
        const walletConnectOptions = {
            projectId: 'a0b855ceaf109dbc8426479a4c3d38d8',
            metadata: {
                name: 'Sample VeChain dApp',
                description: 'A sample VeChain dApp',
                url: window.location.origin,
                icons: [`${window.location.origin}/images/logo/my-dapp.png`],
            },
        };

        DAppKitUI.configure({
            node: 'https://testnet.vechain.org/',
            walletConnectOptions,
            usePersistence: true,
            genesisId: '0x000000000b2bce3c70bc649a02749e8687721b09ed2e15997f466536b20bb127',
            v2Api: {
                enabled: true
            }
        });

        // custom button configuration
        const customButton = document.getElementById('custom-button');
        if (customButton) {
            const handleConnected = (address: string | null): void => {
                if (address) {
                    const formattedAddress = `${address.slice(
                        0,
                        6,
                    )}...${address.slice(-4)}`;
                    customButton.innerText = `Disconnect from ${formattedAddress}`;
                } else {
                    customButton.innerText = 'Connect Custom Button';
                }
            };

            handleConnected(DAppKitUI.wallet.state.address);

            DAppKitUI.modal.onConnectionStatusChange(handleConnected);
        }
    }

    public openModal(): void {
        DAppKitUI.modal.open();
    }

    public sendTx = () =>
        DAppKitUI.signer.sendTransaction({
            clauses: [
                {
                    to: DAppKitUI.wallet.state.address,
                    value: '0x1',
                    data: '0x',
                },
            ],
            comment: 'Send 1 Wei',
        });

    public signTypedData = () =>
        DAppKitUI.signer.signTypedData(
            {
                name: 'Test Data',
                version: '1',
                chainId: 1,
                verifyingContract: '0x435933c8064b4Ae76bE665428e0307eF2cCFBD68',
            },
            { test: [{ name: 'test', type: 'address' }] },
            { test: '0x435933c8064b4Ae76bE665428e0307eF2cCFBD68' },
        );
}

<div class="container">
    <h2>Angular JS</h2>
    <div class="label">kit button:</div>
    <vdk-button></vdk-button>
    <div class="label">custom button:</div>
    <button id="custom-button" (click)="openModal()">
        Connect Custom Button
    </button>
    <div class="label">TX</div>
    <button id="send-tx" (click)="sendTx()">Send TX</button>
    <div class="label">Typed Data</div>
    <button id="typed-data" (click)="signTypedData()">Sign Typed Data</button>
    <button (click)="triggerNull()">
        Trigger connection with no signature
    </button>
    <button (click)="triggerSignTypedData()">
        Trigger connection with typed data
    </button>
    <button (click)="triggerCertificate()">
        Trigger connection with certificate
    </button>
</div>

// examples/sample-vue-app/src/App.vue
<template>
    <div class="container">
        <h2>Vue</h2>
        <div class="label">kit button:</div>
        <vdk-button></vdk-button>
        <div class="label">custom button:</div>
        <button id="custom-button" v-on:click="openModal">
            Connect Custom Button
        </button>
        <div class="label">TX</div>
        <button v-on:click="sendTx">Send TX</button>
        <div class="label">Typed Data</div>
        <button v-on:click="signTypedData">Sign Typed Data</button>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { DAppKitUI } from '@vechain/dapp-kit-ui';

const walletConnectOptions = {
    projectId: 'a0b855ceaf109dbc8426479a4c3d38d8',
    metadata: {
        name: 'Sample VeChain dApp',
        description: 'A sample VeChain dApp',
        url: window.location.origin,
        icons: [`${window.location.origin}/images/logo/my-dapp.png`],
    },
};

const vechainDAppKitOptions = {
    node: 'https://testnet.vechain.org/',
    walletConnectOptions,
    usePersistence: true,
    genesisId: '0x000000000b2bce3c70bc649a02749e8687721b09ed2e15997f466536b20bb127',
    v2Api: {
        enabled: true
    }
};

DAppKitUI.configure(vechainDAppKitOptions);

// custom button configuration

setTimeout(() => {
    const customButton = document.getElementById('custom-button');
    if (customButton) {
        customButton.addEventListener('click', async () => {
            DAppKitUI.modal.open();
        });

        const handleConnected = (address: string | null) => {
            if (address) {
                const formattedAddress = `${address.slice(
                    0,
                    6,
                )}...${address.slice(-4)}`;
                customButton.innerText = `Disconnect from ${formattedAddress}`;
            } else {
                customButton.innerText = 'Connect Custom Button';
            }
        };

        handleConnected(DAppKitUI.wallet.state.address);

        DAppKitUI.modal.onConnectionStatusChange(handleConnected);
    }
}, 100);

export default defineComponent({
    methods: {
        openModal: () => {
            DAppKitUI.modal.open();
        },
        sendTx: () => {
            DAppKitUI.signer.sendTransaction({
                clauses: [
                    {
                        to: DAppKitUI.wallet.state.address,
                       value: '01',
                        data: '0x',
                   },
                ],
                comment: 'Send 1 Wei',
            });
        },
        signTypedData: () => {
            DAppKitUI.signer.signTypedData(
                {
                    name: 'Test Data',
                    version: '1',
                   chainId: 1,
                    verifyingContract:
                        '0x435933c8064b4Ae76bE665428e0307eF2cCFBD68',
                },
               { test: [{ name: 'test', type: 'address' }] },
                { test: '0x435933c8064b4Ae76bE665428e0307eF2cCFBD68' },
            );
        },
    },
});
</script>

<style>
body {
    margin: 0;
    display: flex;
    height: 100vh;
    align-items: center;
    justify-content: center;
}

h2 {
    margin: 0;
}

.container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    border: 1px solid #000;
    border-radius: 20px;
    padding: 20px;
}

.label {
    margin-top: 20px;
    margin-bottom: 10px;
}
</style>
