// apps/sample-vue-app/src/App.vue
<template>
    <div class="container">
        <h2>Vue</h2>
        <div class="label">kit button:</div>
        <vwk-button></vwk-button>
        <div class="label">custom button:</div>
        <button id="custom-button" v-on:click="openModal">Connect Custom Button</button>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { DAppKitUI } from '@vechain/dapp-kit-ui';
import { Genesis } from '@vechain/dapp-kit';

const walletConnectOptions = {
    projectId: 'a0b855ceaf109dbc8426479a4c3d38d8',
    metadata: {
        name: 'Sample VeChain dApp',
        description: 'A sample VeChain dApp',
        url: window.location.origin,
        icons: [`${window.location.origin}/images/logo/my-dapp.png`],
    },
};

const vechainWalletKitOptions = {
    nodeUrl: 'https://testnet.vechain.org/',
    genesis: 'test' as Genesis,
    walletConnectOptions,
    usePersistence: true,
};

DAppKitUI.configure(vechainWalletKitOptions);

// custom button configuration

setTimeout(() => {
    const customButton = document.getElementById('custom-button');
    if (customButton) {
        customButton.addEventListener('click', async () => {
            DAppKitUI.modal.open();
        });

        const handleConnected = (address: string | null) => {
            if (address) {
                const formattedAddress = `${address.slice(0, 6)}...${address.slice(
                    -4,
                )}`;
                customButton.innerText = `Disconnect from ${formattedAddress}`;
            } else {
                customButton.innerText = 'Connect Custom Button';
            }
        };

        handleConnected(DAppKitUI.wallet.state.address);

        DAppKitUI.modal.onConnected(handleConnected);
    }
}, 100);

export default defineComponent({
    methods: {
        openModal:() => {
            DAppKitUI.modal.open();
        }
    },
});
</script>

<style>
    body {
        margin: 0;
        display: flex;
        height: 100vh;
        align-items: center;
        justify-content: center;
    }
    h2 {
        margin: 0;
    }
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        border: 1px solid #000;
        border-radius: 20px;
        padding: 20px;
    }
    .label {
        margin-top: 20px;
        margin-bottom: 10px;
    }
</style>

// examples/sample-angular-app/src/app/app.component.ts
// Angular modules
import { Component, CUSTOM_ELEMENTS_SCHEMA, type OnInit } from '@angular/core';
import { DAppKitUI } from '@vechain/dapp-kit-ui';

@Component({
    selector: 'app-root',
    standalone: true,
    templateUrl: './app.component.html',
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppComponent implements OnInit {
    // -------------------------------------------------------------------------------
    // NOTE Init ---------------------------------------------------------------------
    // -------------------------------------------------------------------------------

    public ngOnInit(): void {
        const walletConnectOptions = {
            projectId: 'a0b855ceaf109dbc8426479a4c3d38d8',
            metadata: {
                name: 'Sample VeChain dApp',
                description: 'A sample VeChain dApp',
                url: window.location.origin,
                icons: [`${window.location.origin}/images/logo/my-dapp.png`],
            },
        };

        DAppKitUI.configure({
            nodeUrl: 'https://testnet.vechain.org/',
            walletConnectOptions,
            usePersistence: true,
        });

        // custom button configuration
        const customButton = document.getElementById('custom-button');
        if (customButton) {
            const handleConnected = (address: string | null): void => {
                if (address) {
                    const formattedAddress = `${address.slice(
                        0,
                        6,
                    )}...${address.slice(-4)}`;
                    customButton.innerText = `Disconnect from ${formattedAddress}`;
                } else {
                    customButton.innerText = 'Connect Custom Button';
                }
            };

            handleConnected(DAppKitUI.wallet.state.address);

            DAppKitUI.modal.onConnectionStatusChange(handleConnected);
        }
    }

    public openModal(): void {
        DAppKitUI.modal.open();
    }

    public sendTx = () =>
        DAppKitUI.signer.sendTransaction({
            clauses: [
                {
                    to: DAppKitUI.wallet.state.address,
                    value: '0x1',
                    data: '0x',

                },
            ],
          comment: 'Send 1 Wei',
        });
}

<div class="container">
    <h2>Angular JS</h2>
    <div class="label">kit button:</div>
    <vdk-button></vdk-button>
    <div class="label">custom button:</div>
    <button id="custom-button" (click)="openModal()">
        Connect Custom Button
    </button>
    <div class="label">TX</div>
    <button id="send-tx" (click)="sendTx()">
      Send
    </button>
</div>
